name: cronschedule workflow
on:
  schedule:
    - cron: "5 * * * *"
env:
MAIL_USER_EMAIL: ${{secrets.MAIL_USER_EMAIL}}
MAIL_USER_PASSWORD: ${{secrets.MAIL_USER_PASSWORD}}
MAIL_FROM: ${{secrets.MAIL_FROM}}
MAIL_TO:{{secrets.MAIL_to}}

jobs:
  run-batch-file:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run batch file1
        run: .\Box.bat
      - name: Run batch file2
        run: .\allclr.bat
