name: cronschedule workflow
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

env:
  MAIL_USER_EMAIL: ${{secrets.MAIL_USER_EMAIL}}
  MAIL_USER_PASSWORD: ${{secrets.MAIL_USER_PASSWORD}}
  MAIL_FROM: ${{secrets.MAIL_FROM}}
  MAIL_TO: ${{secrets.MAIL_TO}}

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: echo "Building..."."
