name: Send email with attachment
on:
  push:
    branches:
      - main
jobs:
  send-email:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with GitHub
        uses: actions/checkout@v2
        with:
         token: ${{ secrets.ACCESS_TOKEN }}
      - name: Report
        run: |
          cp C:\Users\ParimiV\Documents\sample.txt C:\actions-runner\_work\practice-actions\practice-actions\Reports
      - name: Commit and push changes
        run: |
          git config --global user.name 'venkatarao'
          git config --global user.email 'parimivenkat5408@gmail.com'
          git add C:\actions-runner\_work\practice-actions\practice-actions\Reports\.
          git commit -m "Committing report changes"
          git push
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Good Morning team  .
          body: |
            This email contains an attachment.
          from: No-Reply
          to: parimi.venkatarao1662@cientra.com,muralidhar.reddy1655@cientra.com,ajaykarthick.murugan1461@cientra.com,kasibotla.surya1184@cientra.com,praveen.kumar1463@cientra.com,praveen.kumar1463@cientra.com,prathibha.naik1661@cientra.com
          attachments: 'Reports\sample.txt'
