name: periodic workflow
on:
  schedule:
    - cron: "43 09 17 2 *"
jobs:
  run-batch-file:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run batch file1
        run: .\Box.bat
      - name: Run batch file2
        run: .\allclr.bat
