name: Run_repo_contents 
    on: 
     workflow_dispatch:
       inputs:
        component:
       type: choice
      description: 'Select the component to run'        
      required: true        
      default: ''        
      options:          
      - CTM          
     - CMS          
     - HLC
      unit: 
    type: choice
    description: 'Select the unit to run'
     required: true
     default: ''        
     options:
       - unit1
       - unit2
       - unit3
     file_name:
     type: choice
     description: 'Select a file'
     required: true
     default: ''       
     options:  
     - Box          
     - allclr         
      - data
      jobs:
   build:
   runs-on: windows-latest
  steps:
    - name: Checkout code
    uses: actions/checkout@v2
   - name: Run selected unit
    run:  ${{ inputs.component }}/${{ inputs.unit }}/${{ inputs.file_name }}
