name: My Workflow

on: push

jobs:
  my_job:
    runs-on: windows-latest
    steps:
    - name: My Step
      run: echo "Hello, World!"

    # Send email notification only to a specific user
    - name: Email Notification
      if: github.actor == 'your-username'
      uses: dawidd6/action-send-mail@v2.5.0
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Notification: GitHub Action Succeeded'
        to: parimi.venkatarao1662@cientra.com
        from: parimivenkat5408@gmail.com
        body: |
          The GitHub Action was successful!
