name: Email Notification

on:
  push:
    branches: [ main ]

jobs:
  send-email:
    runs-on: windows-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: parimivenkat5408@gmail.com
          subject: Email Notification
          body: 'Hello, this is a test email!'
          to: parimi.venkatarao1662@cientra.com.
